### PR TITLE
added icons for all notifications types

### PR DESCRIPTION
**Pull request by dinumihnea**

### CODE REVIEW

**Comment by dinumihnea** [comment]
notification-success
notification-info
notification-error
notification-warning

**Comment by appreciated** [comment]
Looks really good, will add this enhancement in the evening or tomorrow.

**Comment by appreciated** [comment]
Hi Dinu would you like me to publish the changes straight or do you want to evaluate my changes?

**Comment by dinumihnea** [comment]
Yes sure

**Comment by appreciated** [comment]
What do you think about changing the animation timing function for the indeterminate progressbar to `ease-in-out`?
````
.v-progressbar.indeterminate div.v-progressbar-wrapper div.v-progressbar-indicator {
    animation: indeterminate_progress 1s infinite ease-in-out;
}
````

**Comment by dinumihnea** [comment]
I think is good idea

**Comment by dinumihnea** [comment]
But 1s for large progress bars is too short

**Comment by dinumihnea** [comment]
try `1.5s` or more

**Comment by appreciated** [comment]
I personally think the ease-in-out function compensates the low timing, or actually requires a faster timing because it "feels" slower, I will look up the original material timings. During that you should try it 😉. If we cannot reach an agreement I will make it configurable 😃.

**Comment by dinumihnea** [comment]
Ok, agree with you

**Comment by appreciated** [comment]
I have made some more changes 😅 It would be really great if you could take a look at them

**Comment by dinumihnea** [comment]
Really nice look 😉 so material...

**Pull request merged**
