### PR TITLE
Added switch style for checkbox

### PR DESCRIPTION
**Pull request by dinumihnea**
Switch look for checkbox

### CODE REVIEW

**Review by appreciated — APPROVED** [review]
Would you mind if I change the constant name from SWITCH to CHECKBOX_SWITCH for the sake of consistency?

**Comment by dinumihnea** [comment]
Of course not

**Comment by appreciated** [comment]
I hope you arent disappointed that I changed the default values of the shadow to match the ones of the Materialize Project since I liked them better. 
To make this a compromise I made the shadow configurable to allow you to set the shadow to the previously values.

**Comment by dinumihnea** [comment]
Ok, is good

**Pull request merged**
